version: '2'
services:
  web:
    container_name: flaskdemo
    build: ./web
    image: wtjones/flaskdemo
    command: flask run --host=0.0.0.0 --port 80
    volumes:
      - ./web:/code
    ports:
      - "80:80"
    links:
      - redis:redis
    depends_on:
      - redis
    env_file: .env
  redis:
    container_name: flaskdemoredis
    restart: always
    image: redis
    command: redis-server --appendonly yes
    expose:
      - "6379"
    volumes:
      - ./data:/data